#pragma once

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#define DOCTEST_CONFIG_USE_STD_HEADERS
#define DOCTEST_CONFIG_NO_COMPARISON_WARNING_SUPPRESSION

#define SACO_ASSERT REQUIRE
#define SACO_ASSERT_MSG REQUIRE_MESSAGE

#include <doctest.h>
